<?php

use App\Databases\OcupacionModel;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCatalogoOcupaciones extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('catalogo_ocupaciones', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->timestamps();
            $table->softDeletes();
        });

        $ocupaciones = [
            "ABOGADO/A",
            "ACTOR / ACTRIZ",
            "ACTUARIO/A",
            "ADMINISTRATIVA/O",
            "AGENTE DE BOLSA",
            "AGENTE DE TURISMO",
            "AGENTE INMOBILIARIO",
            "AGRÓNOMA/O",
            "ANALISTA",
            "ANALISTA DE DATOS",
            "ARQUITECTA/O",
            "ARTESANO/A",
            "ARTISTA",
            "ASESOR/A",
            "ASISTENTE SOCIAL",
            "ATLETA",
            "AVICULTOR/A",
            "BACHERA/O",
            "BAILARÍN",
            "BIBLIOTECARIA/O",
            "BIÓLOGA/O",
            "BIOQUÍMICA/O",
            "CADETE",
            "CAJERA/O",
            "CALÍGRAFA/O PÚBLICA",
            "CAMARERO",
            "CANTANTE",
            "CARPINTERA/O",
            "CARTERA/O",
            "CERRAJERA/O",
            "CHOFER",
            "COMMUNITY MANAGER",
            "CONDUCTOR/A",
            "CONSTRUCTOR/A",
            "CONTADOR/A",
            "COSMETÓLOGA/O",
            "DATA ENTRY",
            "DECORADOR/A",
            "DELAGADA/O",
            "DEPORTISTA PROFESIONAL",
            "DESEMPLEADA/O",
            "DIRECTOR/A",
            "DISAÑADOR/A TEXTIL",
            "DISEÑADOR/A",
            "DISEÑADOR/A DE IMAGEN Y SONIDO",
            "DISEÑADOR/A GRÁFICO",
            "DISEÑADOR/A INDUMENTARIA",
            "DISEÑADOR/A INDUSTRIAL",
            "DOCENTE",
            "ECÓLOGA/O",
            "ECONOMISTA",
            "EDITOR/A",
            "EDITOR/A AUDIOVISUAL",
            "EJECUTIVA/O DE CUENTAS",
            "ELECTRICISTA",
            "EMPLEADA/O PÚBLICO",
            "EMPRENDEDOR/A",
            "EMPRESARIA/O",
            "ENCARGADA/O",
            "ENFERMERA/O",
            "ESCRITOR/A",
            "ESCULTOR/A",
            "ESTUDIANTE",
            "FARMACÉUTICA/O",
            "FILÓSOFA/O",
            "FINANCISTA",
            "FLORICULTOR/A",
            "FOTOGRAFA/O",
            "GASISTA",
            "GEÓGRAFA/O",
            "GERENTE",
            "GUÍA DE TURISMO",
            "HELADERA/O",
            "ILUSTRADOR/A",
            "INGENIERO/A AGRÓNOMO",
            "INGENIERO/A AMBIENTAL",
            "INGENIERO/A CIVÍL",
            "INGENIERO/A EN AGRIMENSURA",
            "INGENIERO/A EN ALIMENTOS",
            "INGENIERO/A EN ELECTRÓNICA",
            "INGENIERO/A EN INFORMÁTICA",
            "INGENIERO/A EN MECÁNICA",
            "INGENIERO/A EN PETRÓLEO",
            "INGENIERO/A INDUSTRIAL",
            "INGENIERO/A QUÍMICO",
            "JARDINERA/O",
            "JUBILADA/O",
            "KINESIÓLOGA/O",
            "LOCUTOR/A",
            "MAESTRA/O",
            "MÉDICA/O",
            "MOZA/O",
            "MÚSICA/O",
            "OBRERO/A",
            "ODONTÓLOGA/O",
            "OFTALMÓLOGA/O",
            "OPERADOR/A",
            "OPERADOR/A DE RADIO",
            "OPERARIA/O DE LIMPIEZA",
            "OPERARIA/O DE MANTENIMIENTO",
            "OPERARIA/O DE SEGURIDAD",
            "ORADOR/A",
            "OTRO",
            "PANADERA/A",
            "PELUQUERA/O",
            "PERIODISTA",
            "POLICÍA",
            "PORTERA/O",
            "PRODUCTOR/A",
            "PRODUCTOR/A DE CONTENIDOS",
            "PROFESOR/A",
            "PROGRAMADOR/A",
            "PSICÓLOGO/A",
            "PUBLICISTA",
            "REDACTOR/A",
            "REPARTIDOR/A",
            "REPOSITOR/A",
            "REPOSTERO/A",
            "SECRETARIA/O",
            "SOCIAL MEDIA",
            "TÉCNICA/O",
            "TÉCNICO/A EN HIGIENE Y SEGURIDAD",
            "TRABAJADOR/A SOCIAL",
            "TRADUCTOR/A",
            "TRANSPORTISTA",
            "VENDEDOR/A",
            "VETERINARIA/O",
            "GUIONISTA",
            "",
            "¿MÚSICO?",
            "¿QUÉ ES ESTO?",
            "A CONFIRMAR",
            "A UN AÑO DE SER…",
            "ABOGADO (BASTA DE CRITICAR ABOGADOS,HERNÁN)",
            "ABOGADO (HOMBRE DE CORBATA)",
            "ABOGADO (PERO BUENO EH)",
            "ABUELO/A",
            "ACADÉMICO RETIRADO",
            "ACOMPAÑANTE TERAPÉUTICO",
            "ACTIVISTA",
            "HICE DE TODO.",
            "AL FINAL DEL CAMINO LO VEMOS",
            "ALMACENERO/A",
            "AMA/O DE CASA",
            "AMIGO",
            "ASPIRANTE A...",
            "ASTOLOGO/A",
            "ASTRONAUTA",
            "AÚN BUSCANDO",
            "AUTONOMO/A",
            "BARISTA",
            "BARTENDER",
            "BEBÉ",
            "BECARIA",
            "BOLUDO/A",
            "BOMBERO/A",
            "BRUJA/O",
            "BURÓCRATA",
            "BUSCÁNDOLA",
            "BUSCAVIDAS",
            "CAGADOR",
            "CAMAROGRAFO/A",
            "CAMIONERO/A",
            "CAPO DE CASI NADA",
            "CARA DURA",
            "CASI ALGO",
            "CAZADORA DE HISTORIAS",
            "CEO",
            "CERVECERO/A",
            "CHANTA",
            "CHANTA PROFESIONAL",
            "CIENTIFICO/A",
            "COACH",
            "COCINERO/A",
            "COCINERO/A DEL MONTÓN",
            "COMEDIANTE",
            "CONTENIDISTA",
            "CONTENT ACQUISITIONS MANAGER",
            "CONTENT CREATOR",
            "COPYWRITER",
            "CUALQUIERA",
            "CUALQUIERA MENOS PASAR EL TRAPO",
            "DE TODO UN POCO",
            "DELIVERY",
            "DJ",
            "EN BÚSQUEDA",
            "EN CONSTRUCCIÓN",
            "EN PROCESO",
            "ENOLÓLOGO/A",
            "ENTRENADOR/A",
            "ESCRIBANO/A",
            "EX…",
            "FILOSOFO/A",
            "FREELANCER",
            "FUTURO/A..",
            "GORDO",
            "HIJA/O (PASANTÍA REMUNERADA HASTA QUE ME HAGA DE LOS MEDIOS PARA AUTOABASTECERME, SIEMPRE Y CUANDO ESTUDIE Y BLA BLA)",
            "HOY NO SE",
            "HUMANO",
            "INSERVIBLE",
            "INSPECTOR/A",
            "INVESTIGADOR/A",
            "LO QUE PUEDO",
            "LO QUE SEA",
            "LOCO",
            "LUTHIER",
            "MADRE FULL TIME",
            "MAGO/A",
            "MAMÁ",
            "MAQUILLADOR/A",
            "MEMORIZADOR DE COSAS INÚTILES",
            "MERCADOLOGO/A",
            "MILITAR",
            "MMMMM",
            "NADA",
            "NADA SERIO",
            "NERD",
            "NI IDEA!",
            "NINGUNA",
            "NINI",
            "NINJA",
            "NIÑERA/O",
            "NO SABE NO CONTESTA",
            "NO TENGO",
            "NÓMADA",
            "NOSE",
            "NUNCA SE QUE ESCRIBIR EN ESTA PREGUNTA",
            "NUTRICIONISTA",
            "ODIO ESTA PREGUNTA",
            "PALEONTOLOGA/O",
            "PAPÁ",
            "PERSONA",
            "PERSONAL TRAINER",
            "PINTOR/A",
            "PODCASTER",
            "POETA",
            "PROFESOR/A",
            "PROFETA",
            "QUE BUENA PREGUNTA",
            "QUE SE YO",
            "RECALCULANDO",
            "RECEPCIONISTA",
            "RECURSOS INHUMANOS",
            "REFLEXOLOGO/A",
            "REIKISTA",
            "RETIRADO/A FULL TIME",
            "SACERDOTE",
            "SEXÓLOGO/A",
            "SOLO SE QUE ESTOY FRENTE A UNA COMPUTADORA TODO EL DÍA",
            "SOMELLIER DE COLCHONES",
            "SOMMELIER",
            "STORYTELLER",
            "STREAMER",
            "SUPERVISOR",
            "SUPERVISORA",
            "TAROTISTA",
            "TAROTISTA",
            "TEATRISTA",
            "TERAPEUTA FLORAL",
            "TERAPEUTA HOLÍSTICO",
            "TERAPISTA OCUPACIONAL",
            "TERAPUETA CORPORAL",
            "TERAPUETA HOLISTICA",
            "TESORERO",
            "TESTER",
            "TIRADOR DE CORNERS",
            "TODAVÍA ESTUDIANTE",
            "USER EXPERIENCE RESEARCHER",
            "UX UI DESIGNER",
            "VAGO/A",
            "VARIAS",
            "VIAJERO/A",
        ];
        foreach ($ocupaciones as $ocupacion) {
            $model = new OcupacionModel(["name" => $ocupacion]);
            $model->save();
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('catalogo_ocupaciones');
    }
}
